trigger: none

name: Deploy Static Website

parameters:
- name: azureServiceConnection
  type: string
  default: 'azure-pipeline-conn'
- name: staticSiteStorageName
  type: string
  default: 'web${{ uniqueString(variables['System.TeamProjectId'], variables['Build.Repository.Name']) }}'

variables:
  vmImageName: 'ubuntu-latest'
  frontendFolder: 'frontend'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  displayName: 'Upload static website files to $web container'
  inputs:
    azureSubscription: ${{ parameters.azureServiceConnection }}
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload-batch \
        --account-name ${{ parameters.staticSiteStorageName }} \
        --destination '$web' \
        --source $(frontendFolder) \
        --overwrite
    failOnStandardError: true
